cask_args appdir: '/Applications'

tap 'homebrew/bundle'
tap 'homebrew/completions'

brew 'ack'
brew 'ag'
brew 'brew-gem'
brew 'coreutils'
brew 'ctags'
brew 'docker-completion'
brew 'docker-compose-completion'
brew 'docker-machine-completion'
brew 'fzf'
brew 'go'
brew 'grc'
brew 'imagemagick'
brew 'jp2a'
brew 'jq'
brew 'libcaca', args: ['with-imlib2']
brew 'libgit2'
brew 'neovim'
brew 'node'
brew 'openssl'
brew 'pv'
brew 'readline'
brew 'spaceman-diff'
brew 'tldr'
brew 'tmux'
brew 'unrar'
brew 'vim'
brew 'wget'
brew 'yarn'

###
###
###

cask 'LastPass'
cask 'beyond-compare'
cask 'docker'
cask 'p4v'
cask 'perforce'
cask 'visual-studio-code'
cask 'vlc'
cask 'xquartz'
